networks:
  eShop:

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eShop
      MYSQL_USER: eShop
      MYSQL_PASSWORD: eShop
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - eShop
    ports:
      - "3308:3306"

  app:
    env_file: ./.env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      DB_HOST: mysql
      DB_USERNAME: eShop
      DB_PASSWORD: eShop
      DB_DATANASE: eSHOP
      SALT_ROUNDS: $SALT_ROUNDS
      JWT_SECRET: $JWT_SECRET
      JWT_EXPIRES_IN: $JWT_EXPIRES_IN
    depends_on:
      - mysql
    command: npm run dev
    ports:
      - "3000:3000"
    networks:
      - eShop

volumes:
  mysql:
