networks:
  eShop:

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eShop
      MYSQL_USER: eShop
      MYSQL_PASSWORD: eShop
    networks:
      - eShop
    ports:
      - "3308:3306"
    volumes:
      - mysql:/var/lib/mysql

  api:
    build:
      context: .
      target: production
    depends_on:
      - mysql
    ports:
      - 3000:3000
    networks:
      - eShop

volumes:
  mysql:
