PUT http://localhost:3000/users/11
Content-Type: application/json

{ 
  "lastName": "dana",
  
  "password":"asas"

}
#####################################

DELETE http://localhost:3000/users/10


#####################################

POST http://localhost:3000/users/
Content-Type: application/json

{ 
  
  "lastName": "a12",
  "firstName": "a12",
  "email": "aS21@yahoo.com",
  "password": "jane123"

}
#####################################