POST http://localhost:3000/users/
Content-Type: application/json

{ 
  "lastName":"POPESCU12312",
  "firstName":"ION12312",
  "email":"POPESCU221321@yahoo.com",
  "password":"new password22242"
  
}
#####################################

DELETE http://localhost:3000/users/