DELETE  http://localhost:3000/categories/1

######################


POST http://localhost:3000/categories/
Content-Type: application/json

{
  "name": "Pantofi Sport"
  
}

#############################################
POST http://localhost:3000/categories/
Content-Type: application/json

{
  "name": "Protein Powder",
  "parentId": 25
}

