### Get all orders
GET http://localhost:3000/orders
Content-Type: application/json

###

### Get a specific order by ID
GET http://localhost:3000/orders/1
Content-Type: application/json

###

### Create a new order
POST http://localhost:3000/orders
Content-Type: application/json

{
  "userId": 10,
  "description": "New Order",
  "type": "Type A",
  "status": "Pending"
}

###

POST http://localhost:3000/orders/9/products
Content-Type: application/json

{
  "orderProducts":[
    {
      "productId":1,
      "quantity":3
    }
  ]
}
####
DELETE http://localhost:3000/orders/9/products/1
Content-Type: application/json

{
  "orderProducts":[
    {
      "productId":1,
      "quantity":3
    }
  ]
}






###

### Update an existing order
PUT http://localhost:3000/orders/2
Content-Type: application/json

{
  "description": "Updated Order",
  "type": "Type B",
  "status": "Completed"
}

###

### Delete an order
DELETE http://localhost:3000/orders/26
