### Create a new permission
POST http://localhost:3000/permissions
Content-Type: application/json

{
  "name": "READ",
  "description": "Permission to read data"
}

### Create another permission
POST http://localhost:3000/permissions/
Content-Type: application/json

{
  "name": "WRITE",
  "description": "Permission to write data"
}

### Create another permission
POST http://localhost:3000/permissions/
Content-Type: application/json

{
  "name": "DELETE",
  "description": "Permission to delete data"
}