
POST http://localhost:3000/products
Content-Type: application/json

{
  "name":"telefon1",
  "price":99,
  "stock":22,
  "categories":[1,6],
  "description":"helelo"
}

#######################################


POST http://localhost:3000/products
Content-Type: application/json

{
  "name":"Optim Nutrition Whey Gold",
  "price":99,
  "stock":22,
  "description":"Hig quality whey protein"
}

####################################
POST http://localhost:3000/products/38/categories
Content-Type: application/json

{
"categoryToAdd":36
}

####################################
POST http://localhost:3000/products/38/images
Content-Type: application/json

{
"imageId":1
}
###############################


DELETE http://localhost:3000/products/38/images/1
Content-Type: application/json







###############################
POST http://localhost:3000/products/1/images
Content-Type: application/json

{
  "imageId":2
}




###############################


GET http://localhost:3000/products
Content-Type: application/json


###############################








DELETE http://localhost:3000/users/11
Content-Type: application/json

{ 
  
  "price": 12
  
}
###############################
PUT http://localhost:3000/products/2
Content-Type: application/json

{ 
  "categories":[
    {
      "id": 2
    }
  ]
}
###############################
PUT http://localhost:3000/products/1
Content-Type: application/json

{ 
  "name": "Sony WH-1000XM4",
  "description": "Noise-cancelling over-ear headphones",
  "price": 349.99,
  "stock": 200,
  "categories":[1]
}
###############################
PUT http://localhost:3000/products/10
Content-Type: application/json

{ 
  "name": "Dell XPS 13",
  "description": "High-performance laptop with Intel i7 processor",
  "price": 1199.99,
  "stock": 30,
  "categories":[3,1,2]
}
###############################
POST http://localhost:3000/products/
Content-Type: application/json

{ 
  "name": "Apple MacBook Pro",
  "description": "Apple laptop with M1 chip",
  "price": 1299.99,
  "stock": 20,
  "categories":[1,2]
}
###############################
POST http://localhost:3000/products/
Content-Type: application/json

{ 
  "name": "Google Pixel 6",
  "description": "Google smartphone with Tensor chip",
  "price": 599.99,
  "stock": 80
}
###############################
POST http://localhost:3000/products/
Content-Type: application/json

{ 
  "name": "Amazon Echo Dot",
  "description": "Smart speaker with Alexa",
  "price": 49.99,
  "stock": 300,
  "categories":[1,2]
}
###############################
POST http://localhost:3000/products/
Content-Type: application/json

{ 
  "name": "Nintendo Switch",
  "description": "Hybrid gaming console",
  "price": 299.99,
  "stock": 150
}
###############################
POST http://localhost:3000/products/
Content-Type: application/json

{ 
  "name": "Sony PlayStation 5",
  "description": "Next-gen gaming console",
  "price": 499.99,
  "stock": 10
}
###############################
POST http://localhost:3000/products/
Content-Type: application/json

{ 
  "name": "Samsung Galaxi j6",
  "description": "Un telefon foarte bun",
  "price": 200,
  "stock": 15,
  "categories": [1,6]
}
################################

POST http://localhost:3000/products/2/categories
Content-Type: application/json

{ 
 "categoryToAdd":5
}
############################




DELETE  http://localhost:3000/products/2/categories/5
Content-Type: application/json

{ 
 "categoryToAdd":5
}



###############################
