### Create a new role
POST http://localhost:3000/roles
Content-Type: application/json

{
  "name": "Admin",
  "description": "Administrator role with full permissions",
  "permissions": [1, 2, 3]
}



#####################
DELETE http://localhost:3000/roles/1


############

PUT http://localhost:3000/roles/2
Content-Type: application/json

{
  "name": "Admin",
  "description": "Administrator role with full permissions",
  "permissions": [1, 2,3]
}